export const products = [
  {
    id: 1,
    code: "A-123",
    name: "Product A",
    description: "Product Description",
    image: "/assets/images/products/product_A.jpg",
    variation: "A",
    size: "115 X 231mm",
    color: "Ivory",
    finish: "Gloss",
    price: 99.0,
  },
  {
    id: 2,
    code: "B-123",
    name: "Product B",
    description: "Product Description",
    image: "/assets/images/products/product_A.jpg",
    variation: "B",
    size: "115 X 231mm",
    color: "Ivory",
    finish: "Gloss",
    price: 99.0,
  },
];
